version: '3'
name: 'nuxt-docker-template'
services:
  web:
    build:
      context: '../'
      dockerfile: 'docker/develop.Dockerfile'
    ports:
      - 3000:3000
    # volumes:
    #   - '../src:/src'