version: '3'
name: 'bookkeeping-frontend-develop'
services:
  web:
    build:
      context: '../'
      dockerfile: 'docker/develop.Dockerfile'
    ports:
      - 3000:3000
    volumes:
      - '../src:/src'
      - '/src/node_modules'